<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Hash;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name' => 'Áo Thun Nam Cá Tính',
                'price' => 200000,
                'description' => 'Áo thun với chất liệu vải siêu thấm hút mùi hôi tạo cảm giác thoải mái cho người mặc',
                'discount' => 0,
                'image' => 'aothun.jpg',
                'id_category' => 1, 
                'id_producttype' => 2,
                'id_suppliers' => 1,
                'checkactive' => true,
                'amount' => 100,
                'id' => 1,
            ],
            [
                'name' => 'Quần Jane',
                'price' => 250000,
                'description' => 'Mô tả quần Jane',
                'discount' => 0,
                'image' => 'quan.jpg', 
                'id_category' => 2,
                'id_producttype' => 3,
                'id_suppliers' => 1,
                'checkactive' => true,
                'amount' => 75,
                'id' => 3,
            ],
            [
                'name' => 'Áo Khoác Jane',
                'price' => 400000,
                'description' => 'Mô tả áo khoác Jane',
                'discount' => 0,
                'image' => 'jane.jpg', 
                'id_category' => 1,
                'id_producttype' => 4,
                'id_suppliers' => 1,
                'checkactive' => true,
                'amount' => 50,
                'id' => 4,
            ],
            [
                'name' => 'Quần Thể Thao',
                'price' => 180000,
                'description' => 'Mô tả quần thể thao',
                'discount' => 0,
                'image' => 'quanthethao.jpg', 
                'id_category' => 3,
                'id_producttype' => 1,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 100,
                'id' => 5,
            ],
            [
                'name' => 'Áo Khoác BadHabits',
                'price' => 330000,
                'description' => 'Mô tả áo BadHabits ',
                'discount' => 0,
                'image' => 'AokhoacBadHabits.png', 
                'id_category' => 1,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 6,
            ],
            [
                'name' => 'Áo Khoác Gió Teelab',
                'price' => 299000,
                'description' => 'Mô tả áo Teelab ',
                'discount' => 0,
                'image' => 'AokhoacgioTeelab.png', 
                'id_category' => 1,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 7,
            ],
            [
                'name' => 'Áo Khoác Jane SWE',
                'price' => 179000,
                'description' => 'Mô tả áo Jane SWE ',
                'discount' => 0,
                'image' => 'AokhoacJeanSWE.png', 
                'id_category' => 1,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 8,
            ],
            [
                'name' => 'Áo Thun Teelab',
                'price' => 99000,
                'description' => 'Mô tả áo Teelab ',
                'discount' => 0,
                'image' => 'AothunTeelab.png', 
                'id_category' => 1,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 9,
            ],
            [
                'name' => 'Áo Hoodie BadHabits',
                'price' => 279000,
                'description' => 'Mô tả áo Hoodie ',
                'discount' => 0,
                'image' => 'HoodieBadHabits.png', 
                'id_category' => 1,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 10,
            ],
            [
                'name' => 'Áo PoLo Teelab',
                'price' => 79000,
                'description' => 'Mô tả áo PoLo ',
                'discount' => 0,
                'image' => 'PoloTeelab.png', 
                'id_category' => 1,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 11,
            ],

            [
                'name' => 'Quần Dù SWE',
                'price' => 159000,
                'description' => 'Mô tả quần Dù SWE',
                'discount' => 0,
                'image' => 'QuanDuSWE.png', 
                'id_category' => 3,
                'id_producttype' => 1,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 12,
            ],
            [
                'name' => 'Quần Jane Teelab',
                'price' => 330000,
                'description' => 'Mô tả quần Teelab',
                'discount' => 30,
                'image' => 'QuanJeanTeelab.png', 
                'id_category' => 2,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 13,
            ],
            [
                'name' => 'Quần Short BadHabits',
                'price' => 199000,
                'description' => 'Mô tả quần Short',
                'discount' => 0,
                'image' => 'QuanShortBadHabits.png', 
                'id_category' => 2,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 14,
            ],  
            [
                'name' => 'Quần Short SWE',
                'price' => 179000,
                'description' => 'Mô tả quần Short',
                'discount' => 2,
                'image' => 'QuanShortSWE.png', 
                'id_category' => 2,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 15,
            ],
            [
                'name' => 'Quần Short Teelab',
                'price' => 149000,
                'description' => 'Mô tả quần Short',
                'discount' => 0,
                'image' => 'QuanShortTeelab.png', 
                'id_category' => 2,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 16,
            ],
            [
                'name' => 'Quần Thun BadHabits',
                'price' => 239000,
                'description' => 'Mô tả quần Thun',
                'discount' => 0,
                'image' => 'QuanThunBadHabits.png', 
                'id_category' => 2,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 17,
            ],
            [
                'name' => 'Hoodie Teelab',
                'price' => 339000,
                'description' => 'Mô tả áo Hoodie',
                'discount' => 0,
                'image' => 'TeelabHoodie.png', 
                'id_category' => 1,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 18,
            ],
            [
                'name' => 'Teelab Sweatshirt',
                'price' => 239000,
                'description' => 'Mô tả áo Teelab Sweatshirt',
                'discount' => 3,
                'image' => 'TeelabSweatshirt.png', 
                'id_category' => 1,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 19,
            ],

            [
                'name' => 'Áo Sơ Mi Teelab Cao Cấp',
                'price' => 189000,
                'description' => 'Mô tả áo Sơ Mi Cao Cấp',
                'discount' => 3,
                'image' => 'SomiTeelab.png', 
                'id_category' => 1,
                'id_producttype' => 2,
                'id_suppliers' => 1, 
                'checkactive' => true,
                'amount' => 99,
                'id' => 20,
            ],
        ]);
    }
}
